server:
  port: 19001

spring:
  redis:
    ## 填上你自己的 redis主机
    host: ${redis.host}
    ## 填上你自己的 redis端口
    port: ${redis.port}
    ## 填上你自己的 redis密码，没有就为空
    password: ${redis.password}
    timeout: 1000ms
    database: 1
